const { z } = require('zod');

 const SubjectsEnum = z.enum([
    "Enginnering Chemestry",
    "Introduction to Computer Programming and Data Structure",
    "Enginnering Mathamtics - I",
    "Materials Science",
    "Environment and Ecology",
    "Electrical Engineering & Measurements",
    "Science of Living Systems",
    "Enginnering Mechanics",
    "English for Communication",
    "Enginnering Physics",
    "Workshop Practicals",
    "Enginnering Mathamtics - II",
    "Basic Electronics and Instrumentaion",
    "Electroniccs & Instrumantation",
    "Analog and Digital Electronics",
    "Electromagnetic Field Theory",
    "Electrical Circuit and Systems",
    "Signal System",
    "Advance Engineering Mathematics",
    "Industrial Economics",
    "Electrical Machine-I",
    "Power System-I",
    "Power Electronics",
    "Control Systems",
    "Electrical Measurement and Operating System",
    "Intellectual Property Rights",
    "Artificial Intelligence",
    "Renewable Energy Resources and Converters",
    "Power Generation and Economics",
    "Electrical Machine-II",
    "Advance Power Electronics",
    "Advance Control Systems",
    "Power System-II",
    "VLSI Design Flow – RTL to GDS",
    "Communication System",
    "High Voltage Engineering",
    "Modern Power System Practice",
    "Power System Operation and Control",
    "Signal and System",
    "Solid State Device",
    "Data Structure and Program Design",
    "Network Theory and Systems",
    "Probability and Stochastic Process",
    "Digital Circuits and System Design",
    "Analog Electronics",
    "Analog Communication",
    "Microprocessor and Microcontroller",
    "Elective-I: Soft Computing",
    "Matlab and Python",
    "Control System Engineering",
    "Embedded System and IOT",
    "Digital Communication",
    "VLSI Design",
    "Optical Communication",
    "Mobile and Wireless Communication",
    "Satellite Communication",
    "Soft Computing",
    "Principles of Management",
    "Entrepreneurship",
    "Survey",
    "Strength of Materials",
    "Building Materials and Concrete Technology",
    "Enginnering Geology and Seismology",
    "Fluid Mechanics-I",
    "Building Planning and Drawing Sessional",
    "Construction Technology",
    "Structural Analysis-I",
    "Geotechnical Engineering-I",
    "Fluid Mechanics-II",
    "Transportation Engineering-I",
    "Manufacturing Process-I",
    "Fluid Mechanics",
    "Enginnering Thermodynamics",
    "Mechanics of solids-I",
    "Theory of Machines",
    "Heat and Mass Transfer",
    "Manufacturing Process-II",
    "Applied Thermodynamics-I",
    "Mechanics of solids-II",
    "Digital System Design",
    "Design and Analysis of Algorithms",
    "Data Structures",
    "Introduction to Soft Skills",
    "Probability and Statistics",
    "Discrete Mathematics",
    "Database Management Systems",
    "Computer Organization and Architecture",
    "Operating Systems",
    "Internet and Web Technology"
] , {
    message : "Enter a valid subject"
});


module.exports = {SubjectsEnum}